urls.py
from django.urls import include, path

from . import views

app_name = 'todo'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('<int:list_id>', views.index, name='index'),
    path('<int:list_id>/', views.list, name='list'),
    path('<int:list_id>/add/', views.add, name='add'),
    path('<int:list_id>/remove/', views.remove, name='remove'),
    path('<int:list_id>/delete/', views.delete, name='delete'),
    path('<int:list_id>/list_only/', views.list_only, name='list_only'),
    path('list_list/', views.list_list, name='list_list'),
    path('remove/', views.remove_list, name='remove_list'),
    path('add/', views.add_list, name='add_list'),
]

models.py
from django.db import models

# List of todo items
class List(models.Model):
    user_id = models.CharField(max_length=200)
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=500)

    def __str__(self):
        return self.name

# Todo items
class Item(models.Model):
    user_id = models.CharField(max_length=200)
    todo_list = models.ForeignKey(List, on_delete=models.CASCADE)
    content = models.CharField(max_length=500)
    done = models.BooleanField(default=False)

    def __str__(self):
        return self.content

views.py
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import get_object_or_404, render
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.urls import reverse

from .models import Item, List

def index(request, list_id = 1):
    if request.POST.get('set_id', False):
        request.session['id'] = request.POST['id']

    if not request.session.get('id', False):
        return HttpResponseRedirect(reverse('todo:login'))

    try:
        lists = List.objects.filter(user_id=request.session['id'])
    except:
        lists = False

    try:
        initial_list = lists[0]
        items = Item.objects.filter(todo_list=initial_list)
    except:
        initial_list = False
        items = []

    id = request.session['id']
    context = {'lists':lists, 'list':initial_list, 'items':items, 'id':id}
    return render(request, 'todo/index.html', context)

def list(request, list_id):
    parent_list = get_object_or_404(List, pk=list_id)
    items = Item.objects.filter(todo_list=parent_list)
    context = {'list':parent_list, 'items':items}
    return render(request, 'todo/list.html', context)

def list_only(request, list_id):
    target_list = get_object_or_404(List, pk=list_id)
    items = Item.objects.filter(todo_list=target_list)
    return render(request, 'todo/list_only.html', {'items':items, 'list':target_list})

def list_list(request):
    lists = List.objects.filter(user_id=request.session['id'])
    return render(request, 'todo/list_list.html', {'lists': lists})

def login(request):
    return render(request, 'todo/login.html', {})

@csrf_exempt
def add(request, list_id):
    target_list = get_object_or_404(List, pk=list_id)
    item = Item(todo_list=target_list, content=request.POST['content'], user_id=request.session['id'])
    item.save()
    items = Item.objects.filter(todo_list=target_list)
    return render(request, 'todo/list_only.html', {'items':items, 'list':target_list})

@csrf_exempt
def remove(request, list_id):
    target_list = get_object_or_404(List, pk=list_id)
    item = get_object_or_404(Item, pk=request.POST['item_id'])
    item.done = True
    item.save()
    items = Item.objects.filter(todo_list=target_list)
    return render(request, 'todo/list_only.html', {'items':items, 'list':target_list})

@csrf_exempt
def delete(request, list_id):
    target_list = get_object_or_404(List, pk=list_id)
    if target_list.id == request.session['id']:
        item = get_object_or_404(Item, pk=request.POST['item_id'])
        item.delete()
    items = Item.objects.filter(todo_list=target_list)
    return render(request, 'todo/list_only.html', {'items':items, 'list':target_list})

@csrf_exempt
def add_list(request):
    new_list = List(name=request.POST['name'], description=request.POST['description'], user_id=request.session['id'])
    new_list.save()
    new_list.id
    return HttpResponse(f'{new_list.id}')

@csrf_exempt
def remove_list(request):
    target_list = get_object_or_404(List, pk=request.POST['list_id'])
    target_list.delete()
    if List.objects.filter(user_id=request.session['id']):
       list_id = List.objects.filter(user_id=request.session['id'])[0].id
    else:
       list_id = -1 
    return HttpResponse(f'{list_id}')

templates/todo/add_list.html
<!doctype html>
<html>
<head>
	{% load static %}
	<title>Samiser's Todo List</title>
	<link rel="stylesheet" type="text/css" href="{% static 'todo/css/style.css' %}">
	<script src="{% static 'todo/js/addlist.js' %}"></script>
</head>
<body>
	<div id='content'>
		<h1>Add a List</h1>
		<form action="{% url 'todo:add_list' %}" method="post">
			<ul class="list">
				<li><label for="new_list_name">Name</label>	
				<input name='name' type='text' id='new_list_name'></input></li>
				<li><label for="new_list_description">About</label>	
				<input name='description' type='text' id='new_list_description'></input></li>
				<li><input id="submit" type='submit' value='Add List'></input></li>
		</form>
	</div>
</body>
</html>

templates/todo/index.html
<!doctype html>
<html>
<head>
	{% load static %}
	<title>Samiser's Todo List</title>
	<meta name="viewport" content="width=device-width, initial-scale=1"/> 
	<link rel="stylesheet" type="text/css" href="{% static 'todo/css/style.css' %}">
</head>
<body>
<div id='wrapper'>
	<h1>Samiser's Todo List</h1>
	<h2>{{ id }} <a href="{% url 'todo:login' %}"><button id="change_id">Change ID</button></a></h2>
	<div class='content left' id="list_list">
		{% include 'todo/list_list.html' %}
	</div>

	<div id="todo_list" class='content right'>
		{% include 'todo/list_only.html' with actual_list=list.0 %}
	</div>

	<div id="add_list_div" class='content left'>
		<h1>Add a List</h1>
		<form action="{% url 'todo:add_list' %}" onsubmit="addList(); return false;" method="post">
			<ul class="form_list">
				<li><label for="new_list_name">Name</label>	
				<input name='name' type='text' id='new_list_name'></input></li>
				<li><label for="new_list_description">About</label>	
				<input name='description' type='text' id='new_list_description'></input></li>
				<li><input id="submit" type='submit' value='Add List'></input></li>
			</ul>
		</form>
	</div>
</div>

{% if list %}
<script>
	let list_id = {{ list.id }};
</script>
{% endif %}
<script>
	let url = "{% url 'todo:index' %}";
</script>
<script src="{% static 'todo/js/additem.js' %}"></script>
<script src="{% static 'todo/js/addlist.js' %}"></script>

</body>
</html>

templates/todo/list.html
<!doctype html>
<html>
<head>
	{% load static %}
	<title>Samiser's Todo List</title>
	<link rel="stylesheet" type="text/css" href="{% static 'todo/css/style.css' %}">
	<script src="{% static 'todo/js/additem.js' %}"></script>
</head>
<body>
	<div id='content'>
		<h1>{{ list.name }}</h1>
		<p>{{ list.description }}</p>
		<div class="add" id="add_item">
			<input type="text" id="new_item_content">
			<Button onclick="addItem({{ list.id }})">Add</button>
		</div>
		<div id="todo_list">
			{% include 'todo/list_only.html' %}
		</div>
	</div>
</body>
</html>

templates/todo/list_list.html
<h1>Lists</h1>
{% if lists %}
<ul class="list">
{% for list in lists %}
	<li><a href="{% url 'todo:index' list.id %}" onclick="loadList({{ list.id }}); return false;">{{ list.name }}</a><button onclick="removeList({{ list.id }})">Delete</button></li>
{% endfor %}
</ul>
{% else %}
<p>You don't have any lists</p>
{% endif %}

templates/todo/list_only.html
{% if list %}
<h1>{{ list.name }}</h1>
<p>{{ list.description }}</p>
<ul class="list">
<li class="add" id="add_item">
	<form action="#" onsubmit="addItem({{ list.id }}); return false;">
		<input type="text" id="new_item_content"></input>
		<input id="add_item_submit" type="submit" value="Add"></input>
	</form>
</li>
</ul>

<div>
	<h2>To Do</h2>
	<ul class="list">
	{% for item in items %}
		{% if not item.done %}
		<li><button onclick="doneItem({{ list.id }},{{ item.id }})">Done</button>{{ item.content }}</li>
		{% endif %}
	{% endfor %}
	</ul>

	<h2>Done</h2>
	<ul class="list">
	{% for item in items %}
		{% if item.done %}
			<li><button onclick="deleteItem({{ list.id }},{{ item.id }})">Delete</button>{{ item.content }}</li>
		{% endif %}
	{% endfor %}
	</ul>
</div>
{% else %}
<p>Try adding a list using the form below</p>
{% endif %}

templates/todo/login.html
<!doctype html>
<html>
<head>
	{% load static %}
	<title>Samiser's Todo List</title>
	<meta name="viewport" content="width=device-width, initial-scale=1"/> 
	<link rel="stylesheet" type="text/css" href="{% static 'todo/css/style.css' %}">
</head>
<body>
<div id='wrapper'>
	<h1>Samiser's Todo List</h1>
	<div id="enter_id_form" class='content' style="display: block">
		<h1>Enter ID</h1>
		<form action={% url 'todo:index' %} method="post">
			{% csrf_token %}
			<ul class="form_list">
				<li><input name='id' type='text' id='enter_id'></input>
				<input id="submit" type='submit' value='Enter'></input></li>
				<input type="hidden" id="set_id" name="set_id" value="1">
			</ul>
		</form>
	</div>
</div>

<script src="{% static 'todo/js/addlist.js' %}"></script>
<script src="{% static 'todo/js/additem.js' %}"></script>

</body>
</html>